### PR TITLE
Add ISO digests (closes QubesOS/qubes-issues#2219)

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Note: The digests for Qubes-R1-x86_64-DVD.iso are not PGP-signed.
I have personally verified the signatures on all the other files.

### CODE REVIEW

**Comment by marmarek** [comment]
@rootkovska is this what you had in mind?

**Comment by rootkovska** [comment]
Rather an output of sha*sum *iso. Signed by the usual secpack signers (and only by these keys).

**Comment by andrewdavidwong** [comment]
> Rather an output of sha*sum *iso.

Isn't that what these files contain? Each file contains the `md5sum`, `sha256sum`, and `sha512sum` of its respective ISO.

> Signed by the usual secpack signers (and only by these keys).

Each of these files is signed by the Release Signing Key for its respective release (except `Qubes-R1-x86_64-DVD.iso.DIGESTS`, which is unsigned, and `Qubes-R3.1-rc2-x86_64.iso.DIGESTS`, which is signed by Marek's  Qubes OS signing key, but those two can be fixed).

So, these files would have to be signed, in addition, by the secpack signing keys in order to meet the second requirement. However, may I ask what the rationale is for this second requirement? The Release Signing Keys are already signed by the Qubes Master Signing Key, just like the Security Pack Signing Keys.

**Comment by rootkovska** [comment]
I think it's useful that one can use sha1sum -c hashes to automatically verify all?

**Comment by marmarek** [comment]
On Wed, Aug 03, 2016 at 11:52:24PM -0700, Joanna Rutkowska wrote:
> I think it's useful that one can use sha1sum -c hashes to automatically verify all?

I think no one will download all the ISOs at once. Besides mirroring,
but it's not mirror provider who should check for the integrity.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rootkovska** [comment]
On Thu, Aug 04, 2016 at 12:00:37AM -0700, Marek Marczykowski-Górecki wrote:
> On Wed, Aug 03, 2016 at 11:52:24PM -0700, Joanna Rutkowska wrote:
> > I think it's useful that one can use sha1sum -c hashes to automatically verify all?
> 
> I think no one will download all the ISOs at once. Besides mirroring,
> but it's not mirror provider who should check for the integrity.
> 

Still, doing:

sha1sum -c hashes > /dev/null

is simpler than manually comparing the hashes :P

**Comment by marmarek** [comment]
On Thu, Aug 04, 2016 at 12:02:16AM -0700, Joanna Rutkowska wrote:
> Still, doing:
> 
> sha1sum -c hashes > /dev/null
> 
> is simpler than manually comparing the hashes :P

Of course. And you can do that on the files we have there. Actually you
can use any sha*sum on the same file - it will ignore other hashes.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
> I think it's useful that one can use sha1sum -c hashes to automatically verify all?

You can do that with these files:

```
$ ls
Qubes-R3.1-x86_64.iso 
Qubes-R3.1-x86_64.iso.DIGESTS 
Qubes-R3.2-rc1-x86_64.iso 
Qubes-R3.2-rc1-x86_64.iso.DIGESTS 
Qubes-R3.2-rc2-x86_64.iso 
Qubes-R3.2-rc2-x86_64.iso.DIGESTS
$ sha1sum -c *.DIGESTS
Qubes-R3.1-x86_64.iso: OK
sha1sum: WARNING: 23 lines are improperly formatted
Qubes-R3.2-rc1-x86_64.iso: OK
sha1sum: WARNING: 23 lines are improperly formatted
Qubes-R3.2-rc2-x86_64.iso: OK
sha1sum: WARNING: 23 lines are improperly formatted
```

> Still, doing:
> sha1sum -c hashes > /dev/null
> is simpler than manually comparing the hashes :P

These file are designed to be read by the `*sum` programs (as shown above), so redirection to `/dev/null` and manual comparison are both unnecessary.

**Comment by rootkovska** [comment]
Ah, ok then.

**Comment by marmarek** [comment]
> Qubes-R3.1-rc2-x86_64.iso.DIGESTS, which is signed by Marek's Qubes OS signing key

@andrewdavidwong the file on ftp.qubes-os.org is already signed by release key. Maybe you have some old file?

**Comment by andrewdavidwong** [comment]
Yeah, I must have had an old one. I've updated it and also added the R3.1-rc3 DIGESTS file, which I had left out.

**Comment by andrewdavidwong** [comment]
Is there anything else I should do?

**Comment by marmarek** [comment]
No, that's fine, thanks!

**Pull request merged**
