### PR TITLE
QSB #60: fix typo

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Thank you to user fiftyfourthparallel for pointing out this typo.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
> policy/qubesos/code-signing — Unable to verify (no valid key found)

Is this spurious? My key is indeed available from public keyservers.

**Comment by marmarek** [comment]
> **Edit:** I think the keyservers themselves may be the problem.

Yes, that's exactly the issue. If you know which one is the most reliable nowadays, please let me know, currently we use hkps.pool.sks-keyservers.net

**Comment by andrewdavidwong** [comment]
> Yes, that's exactly the issue. If you know which one is the most reliable nowadays, please let me know, currently we use hkps.pool.sks-keyservers.net

Recently, @mfc recommended https://keys.openpgp.org to me. I haven't had a chance to try it myself yet.

**Comment by marmarek** [comment]
This one mostly works, but the problem is by default it doesn't distribute the full key, unless you (the key owner) confirm to them ownership of the email address in that key.

**Comment by mfc** [comment]
> This one mostly works, but the problem is by default it doesn't distribute the full key, unless you (the key owner) confirm to them ownership of the email address in that key.

not entirely sure the relationship between this typo thread and keyservers, but to clarify that this was an intentional decision by the openpgp.org keyserver, you can read their justification here: 

https://keys.openpgp.org/about

for finding random people's keys, it is not a great keyserver to use. to publishing your own public keys and linking to them for others to download, it is an excellent keyserver to use.

**Pull request merged**
